version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt -t ./package
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
artifacts:
  files:
    - deployment_package.zip